vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
            avatar_image:
                uri_prefix: /images/avatar
                upload_destination: '%kernel.project_dir%/public/images/avatar'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer