vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        user_avatar:
            uri_prefix: uploads/user/avatar
            upload_destination: '%kernel.project_dir%/public/uploads/user/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        article_image:
            uri_prefix: uploads/article/image
            upload_destination: '%kernel.project_dir%/public/uploads/article/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer